########################### NETWORKS
networks:
  wan:
    name: wan
    driver: bridge

  itflow-db:
    name: itflow-db
    external: false

########################### VOLUMES

volumes:
  itflow-db:

########################### ITFLOW
services:
  itflow:
    platform: linux/amd64
    hostname: itflow
    container_name: itflow
    # Comment out image for DockerHub image, use build for local DockerFile if you prefer to build from base
    image: itfloworg/itflow:latest
    #build: 
      #context: .
      #dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: 
      - itflow-db
    networks:
      - wan
      - itflow-db
    ports:
      - "8098:8080"
    environment:
      - TZ=${TZ}
      - ITFLOW_NAME=ITFlow
      - ITFLOW_URL=${ROOT_DOMAIN}
      - ITFLOW_PORT=8080
      - ITFLOW_REPO=github.com/itflow-org/itflow
      - ITFLOW_REPO_BRANCH=master
      - ITFLOW_LOG_LEVEL=info
      - ITFLOW_DB_HOST=${ITFLOW_DB_HOST}
      - ITFLOW_DB_PASS=${ITFLOW_DB_PASS}
    volumes:
      - ../:/var/www/localhost/htdocs
      - ./entrypoint.sh:/usr/bin/entrypoint.sh

  itflow-db:
    hostname: itflow-db
    container_name: itflow-db
    image: mariadb:10.11.6
    restart: always
    ports:
      - "3306:3306"
    networks:
      - itflow-db
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=${ITFLOW_DB_NAME}
      - MARIADB_USER=${ITFLOW_DB_USER}
      - MARIADB_PASSWORD=${ITFLOW_DB_PASS}
    volumes:
      - itflow-db:/var/lib/mysql/    
